services:

  backend:
    build:
      context: ./backend
    container_name: loan-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      STORAGE_PROVIDER: s3
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    container_name: loan-frontend
    depends_on:
      - backend
    ports:
      - "80:80"